/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Samlml
 */
public class JFViajes extends javax.swing.JFrame {

    /**
     * Creates new form JFViajes
     */
    public JFViajes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbBoletos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        txtDestino = new javax.swing.JTextField();
        txtAdulto = new javax.swing.JTextField();
        txtAnciano = new javax.swing.JTextField();
        txtDiscapacitado = new javax.swing.JTextField();
        txtNino = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnConsultarTodo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtViajes = new javax.swing.JTable();
        txtMostraAdulto = new javax.swing.JTextField();
        txtMostraAnciano = new javax.swing.JTextField();
        txtMostraDiscapacitado = new javax.swing.JTextField();
        txtMostraNino = new javax.swing.JTextField();
        txtTotalt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lbBoletos.setText("BOLETOS PARA VIAJES");
        getContentPane().add(lbBoletos);
        lbBoletos.setBounds(140, 20, 130, 20);

        jLabel1.setText("Cliente:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 60, 180, 14);

        jLabel2.setText("Destino:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 90, 80, 14);

        jLabel3.setText("Adulto $100:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 120, 80, 14);

        jLabel4.setText("Anciano $50:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 150, 80, 14);

        jLabel5.setText("Discapacitado $50:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 180, 120, 14);

        jLabel6.setText("Niño $40:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 210, 80, 14);
        getContentPane().add(txtCliente);
        txtCliente.setBounds(140, 60, 90, 20);
        getContentPane().add(txtDestino);
        txtDestino.setBounds(140, 90, 90, 20);
        getContentPane().add(txtAdulto);
        txtAdulto.setBounds(140, 120, 90, 20);
        getContentPane().add(txtAnciano);
        txtAnciano.setBounds(140, 150, 90, 20);
        getContentPane().add(txtDiscapacitado);
        txtDiscapacitado.setBounds(140, 180, 90, 20);
        getContentPane().add(txtNino);
        txtNino.setBounds(140, 210, 90, 20);

        jLabel7.setText("Adulto $");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(340, 44, 100, 30);

        jLabel8.setText("Anciano $");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(340, 74, 100, 30);

        jLabel9.setText("Discapacitado $");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(340, 104, 110, 30);

        jLabel10.setText("Niño $");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(340, 134, 100, 30);

        jLabel11.setText("Total $");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(340, 174, 90, 30);

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular);
        btnCalcular.setBounds(270, 230, 110, 40);

        btnGuardar.setText("Guardar");
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(390, 230, 110, 40);

        btnConsultarTodo.setText("Consultar Todo");
        getContentPane().add(btnConsultarTodo);
        btnConsultarTodo.setBounds(510, 230, 110, 40);

        jtViajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "CLIENTE", "DESTINO", "ADULTO", "ANCIANO", "DISCAPACITADO", "NIÑO", "TOTAL"
            }
        ));
        jScrollPane1.setViewportView(jtViajes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 310, 710, 100);

        txtMostraAdulto.setEditable(false);
        getContentPane().add(txtMostraAdulto);
        txtMostraAdulto.setBounds(470, 50, 70, 20);

        txtMostraAnciano.setEditable(false);
        getContentPane().add(txtMostraAnciano);
        txtMostraAnciano.setBounds(470, 80, 70, 20);

        txtMostraDiscapacitado.setEditable(false);
        getContentPane().add(txtMostraDiscapacitado);
        txtMostraDiscapacitado.setBounds(470, 110, 70, 20);

        txtMostraNino.setEditable(false);
        getContentPane().add(txtMostraNino);
        txtMostraNino.setBounds(470, 150, 70, 20);

        txtTotalt.setEditable(false);
        getContentPane().add(txtTotalt);
        txtTotalt.setBounds(470, 180, 70, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFViajes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCalcular;
    public javax.swing.JButton btnConsultarTodo;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jtViajes;
    public javax.swing.JLabel lbBoletos;
    public javax.swing.JTextField txtAdulto;
    public javax.swing.JTextField txtAnciano;
    public javax.swing.JTextField txtCliente;
    public javax.swing.JTextField txtDestino;
    public javax.swing.JTextField txtDiscapacitado;
    public javax.swing.JTextField txtMostraAdulto;
    public javax.swing.JTextField txtMostraAnciano;
    public javax.swing.JTextField txtMostraDiscapacitado;
    public javax.swing.JTextField txtMostraNino;
    public javax.swing.JTextField txtNino;
    public javax.swing.JTextField txtTotalt;
    // End of variables declaration//GEN-END:variables
}
